### ISSUE TITLE
Ubuntu and Debian packages depend on gstreamer0.10-plugins-base, which is no longer available in recent Ubuntu / Debian versions

### ISSUE THREAD

**Issue by logix2** [cges30901/hmtimer#2]
The hmtimer PPA packages depend on gstreamer0.10-plugins-base even for Ubuntu 18.04 and 18.10, but gstreamer0.10-plugins-base is not available in newer Ubuntu releases. The last Ubuntu release to include this is Ubuntu 16.04 (Xenial), as you can see here: https://launchpad.net/ubuntu/+source/gst-plugins-base0.10

I don't use Debian, but I see that the OBS Debian package also depends on gst-plugins-base0.10, which is not available in Debian 9 (Stretch).

**Comment by cges30901** [comment]
Thank you for reporting this issue. I will fix it soon.

**Comment by cges30901** [comment]
Hello. I uploaded new packages for Ubuntu 16.04, 18.04, 18.10 and Debian. Now I think they can be installed without error.

**Comment by logix2** [comment]
Thank you, it works great now!
